fel:
  openai:
    api-base: 'https://api.siliconflow.cn/v1'
    api-key: 'sk-jujmjfaevrwyxtsyyrvpwlkwrbwwoxrjsdfpjcokwobflxqy'
example:
  model:
    chat: 'Qwen/Qwen2.5-72B-Instruct'
    embed: 'BAAI/bge-large-zh-v1.5'